const SOURCES = {
 intro: {file:'1.2 Introduccion impacto de las Redes.pptx.pdf',label:'Impacto de las redes'},
 devices:{file:'2.1 Dipositivos de Red.pptx.pdf',label:'Dispositivos de red'},
 media:{file:'2.2 Medios de transmision.pptx.pdf',label:'Medios de transmisión'},
 ip:{file:'15.1 Direccionamiento IP parte 1.pptx.pdf',label:'Direccionamiento IP'},
 subnet:{file:'3.1 Subnetting.pptx.pdf',label:'Subnetting'},
 arch:{file:'5.1 Arquitectura de Red (2).pptx',label:'Arquitectura de red'},
 osi:{file:'7.1 Modelo de Referencia OSIISO y TCPIP (1).pptx',label:'Modelos OSI y TCP/IP'},
 topology:{file:'image (1).png',label:'Topología Packet Tracer'}
};
const ref=(key,where)=>({key,where});
const TOPICS=[
 {id:'fundamentos',title:'Comunicación y redes',unit:'Fundamentos',priority:'media',why:'Base conceptual de las primeras clases y del resto del temario.',sources:[ref('intro','pp. 2–6, 11–15'),ref('arch','diaps. 3–4')],simple:'Una red permite que dispositivos intercambien mensajes. Para entender cualquier comunicación, identifica quién envía, quién recibe, qué información viaja, por qué medio y con qué reglas.',academic:'El curso reúne cuatro elementos: dispositivos, medios, mensajes y protocolos. Los protocolos acuerdan identidad de emisor y receptor, formato, ritmo y confirmación. La convergencia integra voz, video y datos sobre una infraestructura compartida. Las redes sostienen colaboración, trabajo, educación, servicios y entretenimiento.',keys:['Emisor y destinatario','Mensaje','Medio','Protocolo','Convergencia'],example:'Una videollamada usa equipos finales, enlaces cableados o inalámbricos, paquetes de voz y video y reglas comunes para que los extremos se entiendan.',steps:['Identifica los extremos.','Reconoce el medio y los dispositivos intermedios.','Nombra las reglas que permiten interpretar y entregar los datos.'],mistake:'Confundir Internet con una sola red física: es una interconexión de redes.',exam:'¿Qué cuatro componentes básicos hacen posible la comunicación en red?',answer:'Dispositivos, medios, mensajes y reglas o protocolos.'},
 {id:'dispositivos',title:'Dispositivos y topología',unit:'Fundamentos',priority:'alta',why:'Aparece en dos PDF, en arquitectura y en la imagen práctica.',sources:[ref('devices','pp. 2–8'),ref('media','pp. 3–5'),ref('arch','diap. 3'),ref('topology','imagen completa')],simple:'Los equipos finales producen o consumen datos. Los switches unen equipos de una red local; los routers enlazan redes distintas.',academic:'El material distingue dispositivos de usuario final y dispositivos de red. La investigación propuesta enumera switches administrables, no administrables, de capa 2 y capa 3; routers core, edge, frontera y Wi‑Fi; y puntos de acceso de varios modos de gestión. En la topología de Packet Tracer hay dos LAN laterales con un equipo final y un switch cada una, tres routers interconectados en triángulo y un servidor conectado al router inferior.',keys:['Host final','Switch','Router','Access point','LAN','Enlace redundante'],example:'Para ir de Laptop0 a PC0, el tráfico pasa por Switch0, Router1, una ruta entre routers, Router2, Switch1 y PC0. El triángulo ofrece más de una ruta entre Router1 y Router2.',steps:['Ubica origen y destino.','Traza los enlaces hasta el primer router.','Elige un camino entre routers.','Continúa hasta la LAN destino.'],mistake:'Un switch común no sustituye al router para comunicar subredes IP distintas.',exam:'En la imagen, ¿qué cambia si falla el enlace directo Router1–Router2?',answer:'Puede existir una ruta alternativa Router1–Router0–Router2 si el enrutamiento está configurado; la imagen por sí sola no demuestra que haya rutas configuradas.',visual:'topology'},
 {id:'medios',title:'Medios de transmisión',unit:'Fundamentos',priority:'alta',why:'Tiene 17 páginas y un ejercicio con seis escenarios resueltos.',sources:[ref('media','pp. 5–17'),ref('arch','diap. 3')],simple:'El medio es el camino por el que viajan los datos: cobre, fibra o radio. Se elige por distancia, velocidad, interferencia, movilidad y costo.',academic:'La presentación separa medios guiados y no guiados. Destaca UTP, fibra multimodo, fibra monomodo, Wi‑Fi, WiMAX y satélite. También clasifica antenas direccionales, omnidireccionales y sectoriales. Su ejercicio asocia Cat 6A con LAN de hasta 100 m y 10 Gbps; multimodo con cientos de metros; monomodo con largas distancias; Wi‑Fi con movilidad local; WiMAX con cobertura de kilómetros; satélite con sitios remotos.',keys:['Guiado / no guiado','UTP','Fibra multimodo','Fibra monomodo','Wi‑Fi / WiMAX'],example:'Si dos edificios están separados por cientos de metros y hay interferencia eléctrica, la respuesta esperada del curso es fibra multimodo.',steps:['Mide distancia.','Define velocidad y movilidad requeridas.','Revisa interferencias e infraestructura disponible.','Justifica el medio elegido.'],mistake:'Tomar las distancias de una diapositiva como límite universal: dependen del estándar, equipo y entorno.',exam:'¿Qué medio escogerías para una sede aislada sin infraestructura terrestre y por qué?',answer:'Según el ejercicio del curso, satélite por su alcance en sitios remotos.'},
 {id:'arquitectura',title:'Arquitectura, QoS y seguridad',unit:'Diseño',priority:'alta',why:'Cuatro características desarrolladas con notas, diagramas y ejemplos.',sources:[ref('arch','diaps. 2, 4–11'),ref('intro','p. 10')],simple:'Una buena red debe seguir funcionando ante fallas, crecer, priorizar el tráfico sensible y proteger datos y equipos.',academic:'Las cuatro propiedades del material son tolerancia a fallos, escalabilidad, calidad de servicio (QoS) y seguridad. La redundancia elimina puntos únicos de falla. QoS gestiona congestión y puede priorizar voz y video sobre descargas. La seguridad cubre infraestructura y contenido; el curso asocia autenticación y cifrado con confidencialidad, firmas con integridad y redundancia con disponibilidad.',keys:['Tolerancia a fallos','Escalabilidad','QoS','Confidencialidad','Integridad','Disponibilidad'],example:'Dos proveedores de Internet permiten seguir operando si uno falla; una videollamada con prioridad evita cortes durante descargas.',steps:['Localiza puntos únicos de falla.','Proyecta crecimiento de usuarios.','Ordena tráfico por sensibilidad al retardo.','Protege acceso, datos y continuidad.'],mistake:'Pensar que redundancia garantiza continuidad por sí sola: requiere rutas y conmutación funcionales.',exam:'¿Qué característica mejora al priorizar voz frente a una descarga?',answer:'La calidad de servicio (QoS).'},
 {id:'modelos',title:'Capas OSI y TCP/IP',unit:'Modelos',priority:'alta',why:'La presentación más extensa dedica 34 diapositivas a capas, PDU y protocolos.',sources:[ref('osi','diaps. 1, 5–18, 30–34')],simple:'Los modelos de capas dividen la comunicación en tareas. Cada capa usa los servicios de la anterior y entrega datos a la siguiente.',academic:'OSI tiene siete capas: física, enlace, red, transporte, sesión, presentación y aplicación. TCP/IP se presenta con cuatro: acceso a red, Internet, transporte y aplicación. Aplicación, presentación y sesión de OSI se agrupan en aplicación TCP/IP; red corresponde a Internet; física y enlace a acceso a red. Encapsular significa añadir información de control al bajar por la pila; al recibir, se retira en sentido inverso.',keys:['OSI 7 capas','TCP/IP 4 capas','Encapsulación','PDU','Trama','Paquete','Segmento'],example:'Al abrir una web, HTTP opera en aplicación; TCP puede llevar segmentos; IP determina el paquete y su ruta; Ethernet/Wi‑Fi lo transporta como trama por el enlace.',steps:['Parte de los datos de aplicación.','Añade cabecera de transporte: segmento.','Añade cabecera IP: paquete.','Añade información de enlace: trama.','Transmite bits por el medio.'],mistake:'Asignar una función a una capa solo porque su nombre suena parecido: compara la tarea real, por ejemplo IP enruta en capa de red.',exam:'Ordena las PDU de transporte, red, enlace y física.',answer:'Segmento, paquete, trama y bits.',visual:'osi'},
 {id:'transporte',title:'TCP, UDP y puertos',unit:'Modelos',priority:'alta',why:'Las diapositivas 15 y 19–29 incluyen ejemplos y secuencias visuales.',sources:[ref('osi','diaps. 15–29')],simple:'TCP agrega control para que una conversación pueda ordenar y confirmar datos; UDP envía con menos control. Los puertos distinguen aplicaciones en el mismo equipo.',academic:'El curso destaca secuenciación, confirmaciones (ACK), buffers, control de flujo y ventana TCP. El diagrama de tres pasos muestra SYN del cliente, SYN‑ACK del servidor y ACK del cliente. Los puertos identifican servicios y conversaciones; IP identifica los equipos. UDP no ofrece las mismas garantías de entrega y orden que TCP.',keys:['TCP','UDP','Puerto','ACK','Ventana','SYN → SYN‑ACK → ACK'],example:'Una transferencia FTP usa TCP según la diapositiva; TFTP usa UDP. En el establecimiento TCP, el servidor confirma la petición SYN y el cliente confirma la respuesta.',steps:['Cliente envía SYN.','Servidor responde SYN‑ACK.','Cliente envía ACK.','Después se intercambian datos con números de secuencia y confirmaciones.'],mistake:'Confundir una conexión TCP confiable con una garantía absoluta de que la aplicación final procesó el dato.',exam:'¿Para qué sirven los puertos si el equipo ya tiene IP?',answer:'Para distinguir servicios y conversaciones de distintas aplicaciones en el mismo host.',visual:'handshake'},
 {id:'ip',title:'IPv4, máscaras y CIDR',unit:'Direccionamiento',priority:'alta',why:'Es requisito directo para los ejercicios de subredes y aparece en dos archivos.',sources:[ref('ip','pp. 2, 4, 7–11'),ref('subnet','pp. 7, 9–15')],simple:'Una IPv4 tiene 32 bits, escritos como cuatro octetos. La máscara indica qué bits identifican la red y cuáles al host.',academic:'La notación CIDR /n indica n bits de red. Por ejemplo 192.168.1.5/24 tiene máscara 255.255.255.0 y pertenece a 192.168.1.0/24. La dirección de red identifica la subred; broadcast es su extremo superior; normalmente las direcciones intermedias se asignan a hosts. La presentación compara IPv4 público/privado, NAT, subnetting e IPv6 ante el agotamiento del espacio IPv4.',keys:['32 bits','4 octetos','Máscara','Prefijo CIDR','Red / host','Broadcast'],example:'192.168.1.50/24: red .0, primer host .1, último .254, broadcast .255; 254 hosts utilizables.',steps:['Convierte /n a máscara.','Calcula red con IP AND máscara.','Pon bits de host en 1 para broadcast.','Suma/resta uno para el rango usual de hosts.'],mistake:'En la diapositiva 8 hay un ejemplo que empieza con 176.16.20.31 y termina con 172.16.20.31/16: son direcciones distintas; conserva el primer octeto correcto al convertir.',exam:'¿Qué expresa /24?',answer:'Que 24 de los 32 bits de IPv4 pertenecen al prefijo de red.'},
 {id:'subnetting',title:'Subnetting y rangos',unit:'Direccionamiento',priority:'alta',why:'24 páginas con tres ejemplos y un ejercicio explícito; máxima carga de cálculo.',sources:[ref('subnet','pp. 2, 7, 11–24'),ref('ip','pp. 9–11')],simple:'Subnetear es tomar bits antes reservados a hosts para crear redes más pequeñas. Cada bit prestado duplica el número de subredes y reduce la capacidad de hosts.',academic:'Si se parte de /24 y se usa /26, se prestan 2 bits: 2² = 4 subredes. Quedan 6 bits de host: 2⁶ = 64 direcciones por subred, de las cuales 62 son hosts utilizables en una subred convencional. El salto es 256 − 192 = 64 en el último octeto. Las redes son .0, .64, .128 y .192. La fórmula 2ⁿ−2 para subredes aparece como regla de routers antiguos; el propio curso indica 2ⁿ para equipos actuales.',keys:['Bits prestados','2ⁿ subredes','2ʰ−2 hosts usuales','Salto','Red','Broadcast'],example:'192.168.10.0/26 produce 192.168.10.0–63, .64–127, .128–191 y .192–255; en la primera, hosts .1–.62.',steps:['Define prefijo original y nuevo.','Calcula bits prestados y bits de host.','Obtén subredes y hosts utilizables.','Calcula máscara y salto.','Enumera red, primer host, último host y broadcast.'],mistake:'La diapositiva 19 llama “64 hosts” al resultado 2⁶; son 64 direcciones totales y 62 hosts utilizables. Tampoco apliques 2ⁿ−2 a subredes modernas.',exam:'Para 192.168.10.0/27, ¿cuántas subredes /27 caben en /24 y cuántos hosts utilizables tiene cada una?',answer:'8 subredes (2³) y 30 hosts utilizables por subred (2⁵−2).',visual:'subnet'},
 {id:'ruteo',title:'Ruteo y lectura de topologías',unit:'Aplicación',priority:'media',why:'Se conecta con routers, OSI, arquitectura y la imagen de práctica.',sources:[ref('osi','diaps. 20, 30–31'),ref('arch','diaps. 6–7'),ref('topology','imagen completa')],simple:'El router decide por dónde enviar un paquete cuando el destino está en otra red.',academic:'Las diapositivas atribuyen a routers interconexión de redes, selección de camino, conmutación y filtrado de paquetes. El grafo del material muestra LAN de acceso, proveedores regionales y backbone con caminos alternativos. En la imagen de Packet Tracer, Router1 y Router2 conectan las LAN laterales y Router0 conecta el servidor; los tres routers forman un triángulo. Las líneas rojas visibles pueden indicar enlace caído o sin operación en Packet Tracer; la captura sola no permite confirmar la causa.',keys:['Tabla de rutas','Siguiente salto','Red destino','Ruta alternativa','Punto único de falla'],example:'Laptop0 y PC0 requieren direccionamiento, puerta de enlace y rutas entre routers para comunicarse; tener cables dibujados no basta.',steps:['Identifica subred origen y destino.','Determina gateway del host.','Sigue el siguiente salto de cada router.','Comprueba enlace, máscara y ruta de retorno.'],mistake:'Asumir que un enlace redundante se usará automáticamente sin protocolo o rutas apropiadas.',exam:'¿Qué verificas si la laptop no alcanza el servidor?',answer:'IP y máscara de laptop, gateway, estado de enlaces, direcciones de interfaces, rutas de ida y vuelta y filtros.'}
];
const EXERCISES=[
 {id:'ex1',topic:'fundamentos',level:'Fácil',title:'Los cuatro elementos',prompt:'En una clase por videollamada, identifica dispositivos, medio, mensaje y reglas.',hint:'Piensa en quién habla, cómo viajan los datos y cómo se interpretan.',solution:'1. Dispositivos: computadoras/teléfonos y equipos de red. 2. Medio: cable, fibra o radio. 3. Mensajes: audio, video y control. 4. Reglas: protocolos que permiten direccionar, transportar y presentar los datos.',source:ref('arch','diap. 3')},
 {id:'ex2',topic:'medios',level:'Intermedio',title:'Selecciona un medio',prompt:'Debes conectar dos edificios separados por varios cientos de metros con alta velocidad y mucha interferencia eléctrica. Elige y justifica.',hint:'Revisa el escenario 2 de la tabla del curso.',solution:'1. La distancia supera el tramo UTP típico del ejercicio. 2. La interferencia desaconseja cobre. 3. El material propone fibra óptica multimodo: alta velocidad, cientos de metros e inmunidad a interferencia electromagnética.',source:ref('media','p. 17')},
 {id:'ex3',topic:'arquitectura',level:'Fácil',title:'QoS en congestión',prompt:'Una llamada se corta mientras se descargan archivos. ¿Qué característica de arquitectura aplicarías?',hint:'Busca la propiedad que ordena tráfico por sensibilidad al retardo.',solution:'Aplicar QoS: identificar tráfico de voz/video, darle prioridad sobre descargas y comprobar que el enlace tenga capacidad suficiente. La prioridad reduce el efecto de congestión, pero no crea ancho de banda.',source:ref('arch','diaps. 8, 11')},
 {id:'ex4',topic:'modelos',level:'Intermedio',title:'Sigue la encapsulación',prompt:'Ordena dato, segmento, paquete, trama y bits desde la aplicación hasta el medio.',hint:'Cada capa inferior añade información de control.',solution:'Dato de aplicación → segmento de transporte → paquete IP → trama de enlace → bits en el medio. El receptor invierte el proceso.',source:ref('osi','diaps. 5–7, 21')},
 {id:'ex5',topic:'transporte',level:'Intermedio',title:'Apertura TCP',prompt:'Un cliente inicia una conexión TCP. Escribe los tres mensajes de establecimiento y quién envía cada uno.',hint:'El segundo mensaje confirma y solicita a la vez.',solution:'1. Cliente → servidor: SYN. 2. Servidor → cliente: SYN‑ACK. 3. Cliente → servidor: ACK. La imagen incrustada muestra además números de secuencia y confirmación.',source:ref('osi','diaps. 23–24')},
 {id:'ex6',topic:'ip',level:'Fácil',title:'Rango de un /24',prompt:'Calcula red, primer host, último host y broadcast de 192.168.1.50/24.',hint:'La máscara es 255.255.255.0.',solution:'1. /24 deja 8 bits de host. 2. Red: 192.168.1.0. 3. Broadcast: 192.168.1.255. 4. Hosts usuales: .1 a .254; 254 en total.',source:ref('ip','p. 11')},
 {id:'ex7',topic:'subnetting',level:'Intermedio',title:'Subredes /27',prompt:'Divide 192.168.10.0/24 en /27. Indica máscara, salto, número de subredes y hosts utilizables.',hint:'Se prestan 3 bits; quedan 5 de host.',solution:'1. Máscara: 255.255.255.224. 2. Salto: 256−224=32. 3. 2³=8 subredes: .0, .32, .64, .96, .128, .160, .192, .224. 4. Cada una tiene 2⁵=32 direcciones y 30 hosts utilizables.',source:ref('subnet','p. 20')},
 {id:'ex8',topic:'subnetting',level:'Difícil',title:'¿Caben 31 hosts?',prompt:'Una red /24 debe tener al menos dos subredes con 31 hosts utilizables cada una. Encuentra el prefijo más largo posible y explica por qué /27 no sirve.',hint:'Comprueba 2ʰ−2 ≥ 31.',solution:'1. Con 5 bits de host, 2⁵−2=30: /27 no alcanza. 2. Con 6 bits, 2⁶−2=62: /26 sí. 3. /24 → /26 presta 2 bits y ofrece 4 subredes modernas. El resultado coincide con el ejemplo 3 del curso.',source:ref('subnet','pp. 23–24')},
 {id:'ex9',topic:'ruteo',level:'Difícil',title:'Falla en la topología',prompt:'Si se interrumpe el enlace directo Router1–Router2, ¿qué camino físico alternativo existe y qué configuración falta comprobar?',hint:'Observa el triángulo entre los tres routers.',solution:'1. Camino físico: Router1 → Router0 → Router2. 2. Comprueba interfaces activas, direcciones IP, rutas de ida y vuelta o protocolo de enrutamiento. 3. La imagen solo muestra la conexión física; no prueba la recuperación lógica.',source:ref('topology','imagen completa')},
 {id:'ex10',topic:'subnetting',level:'Difícil',title:'Doce subredes',prompt:'Desde una /24, crea al menos 12 subredes de tamaño igual. ¿Qué prefijo, máscara y hosts utilizables obtienes?',hint:'Busca el menor n con 2ⁿ ≥ 12.',solution:'1. 2³=8 es insuficiente; 2⁴=16 alcanza. 2. Nuevo prefijo /28; máscara 255.255.255.240. 3. Quedan 4 bits de host: 16 direcciones y 14 hosts utilizables por subred. El curso presenta /28 en su ejemplo 2.',source:ref('subnet','pp. 21–22')}
];
const QUESTIONS=[
 {id:'q1',topic:'fundamentos',type:'mc',level:'Fácil',ask:'¿Cuál conjunto contiene los cuatro elementos básicos de una red?',options:['Dispositivos, medios, mensajes y reglas','Hosts, dominios, antivirus y nube','Cables, direcciones MAC, DNS y energía'],answer:0,explain:'El material enumera dispositivos, medios, mensajes y reglas/protocolos.',wrong:['','La lista mezcla servicios y conceptos que no son los cuatro elementos.','Son componentes posibles, pero no la clasificación del curso.'],source:ref('arch','diap. 3')},
 {id:'q2',topic:'dispositivos',type:'mc',level:'Fácil',ask:'¿Qué equipo interconecta redes IP diferentes?',options:['Switch de acceso','Router','Equipo final'],answer:1,explain:'El router selecciona caminos entre redes.',wrong:['Un switch común conecta equipos de una LAN.','','El equipo final origina o recibe datos.'],source:ref('osi','diap. 31')},
 {id:'q3',topic:'medios',type:'mc',level:'Intermedio',ask:'¿Qué medio propone la tabla del curso para distancias de decenas de kilómetros?',options:['UTP Cat 6A','Fibra monomodo','Wi‑Fi local'],answer:1,explain:'La tabla reserva fibra monomodo para largas distancias y baja atenuación.',wrong:['El ejemplo UTP llega hasta 100 m.','','Wi‑Fi se plantea como acceso local.'],source:ref('media','p. 17')},
 {id:'q4',topic:'arquitectura',type:'tf',level:'Fácil',ask:'QoS puede priorizar voz y video sobre descargas durante la congestión.',options:['Verdadero','Falso'],answer:0,explain:'Esa es la decisión de prioridad descrita en la presentación.',wrong:['','La presentación sí da este ejemplo.'],source:ref('arch','diap. 8')},
 {id:'q5',topic:'modelos',type:'mc',level:'Intermedio',ask:'¿Qué capa OSI se encarga del ruteo?',options:['Transporte','Red','Enlace de datos'],answer:1,explain:'La capa de red elige la ruta de los paquetes.',wrong:['Transporte gestiona comunicación extremo a extremo.','','Enlace maneja tramas del enlace local.'],source:ref('osi','diaps. 12, 30–31')},
 {id:'q6',topic:'transporte',type:'mc',level:'Intermedio',ask:'¿Cuál es el orden del inicio de una conexión TCP?',options:['ACK → SYN → SYN‑ACK','SYN → SYN‑ACK → ACK','SYN → ACK → SYN‑ACK'],answer:1,explain:'El cliente solicita, el servidor responde y el cliente confirma.',wrong:['ACK no inicia la conexión.','','El ACK final va después del SYN‑ACK.'],source:ref('osi','diaps. 23–24')},
 {id:'q7',topic:'ip',type:'fill',level:'Fácil',ask:'Completa: una dirección IPv4 contiene ___ bits.',answer:'32',explain:'Son cuatro octetos de ocho bits cada uno.',source:ref('ip','p. 4')},
 {id:'q8',topic:'ip',type:'mc',level:'Intermedio',ask:'¿Qué máscara corresponde a /24?',options:['255.255.0.0','255.255.255.0','255.255.255.192'],answer:1,explain:'Los 24 bits de red llenan los tres primeros octetos.',wrong:['Corresponde a /16.','','Corresponde a /26.'],source:ref('ip','p. 8')},
 {id:'q9',topic:'subnetting',type:'mc',level:'Intermedio',ask:'¿Cuántos hosts utilizables tiene una subred /26 convencional?',options:['64','62','30'],answer:1,explain:'2⁶=64 direcciones; al reservar red y broadcast quedan 62 hosts.',wrong:['64 es el número total de direcciones.','','30 corresponde a /27.'],source:ref('subnet','pp. 16–19')},
 {id:'q10',topic:'subnetting',type:'fill',level:'Intermedio',ask:'Completa: el salto de 192.168.10.0/27 en el último octeto es ___.',answer:'32',explain:'La máscara /27 termina en 224; 256−224=32.',source:ref('subnet','p. 20')},
 {id:'q11',topic:'subnetting',type:'mc',level:'Difícil',ask:'Desde /24, ¿qué prefijo permite al menos 12 subredes iguales?',options:['/27','/28','/26'],answer:1,explain:'Se necesitan cuatro bits prestados: 2⁴=16 subredes, por tanto /28.',wrong:['/27 ofrece ocho.','','/26 ofrece cuatro.'],source:ref('subnet','pp. 21–22')},
 {id:'q12',topic:'ruteo',type:'tf',level:'Intermedio',ask:'En la topología proporcionada, el triángulo de routers demuestra por sí solo que existe conmutación automática ante fallas.',options:['Verdadero','Falso'],answer:1,explain:'La imagen muestra enlaces físicos; faltan datos de rutas y configuración para concluirlo.',wrong:['La conexión física no demuestra rutas configuradas.',''],source:ref('topology','imagen completa')},
 {id:'q13',topic:'modelos',type:'match',level:'Intermedio',ask:'Relaciona cada PDU con su capa.',pairs:[['Transporte','Segmento'],['Red','Paquete'],['Enlace','Trama']],explain:'Al bajar por las capas cambia la unidad: segmento, paquete y trama.',source:ref('osi','diaps. 7, 21, 27')},
 {id:'q14',topic:'medios',type:'tf',level:'Fácil',ask:'El material clasifica las antenas como direccionales, omnidireccionales y sectoriales.',options:['Verdadero','Falso'],answer:0,explain:'Son las tres clases listadas en la diapositiva.',wrong:['','Sí aparecen las tres clases.'],source:ref('media','p. 14')},
 {id:'q15',topic:'arquitectura',type:'mc',level:'Intermedio',ask:'¿Qué acción combate un punto único de falla?',options:['Agregar redundancia','Reducir la máscara IP','Usar solo UDP'],answer:0,explain:'La tolerancia a fallos se apoya en enlaces y equipos alternativos.',wrong:['','La máscara no crea continuidad de servicio.','UDP no sustituye redundancia.'],source:ref('arch','diaps. 5–7')},
 {id:'q16',topic:'transporte',type:'tf',level:'Intermedio',ask:'Los puertos permiten distinguir aplicaciones que usan la misma dirección IP.',options:['Verdadero','Falso'],answer:0,explain:'El material explica que varios circuitos de aplicación pueden coexistir en un host.',wrong:['','La IP identifica al host; el puerto ayuda a identificar el servicio.'],source:ref('osi','diap. 25')},
 {id:'q17',topic:'ip',type:'mc',level:'Intermedio',ask:'¿Cuál de estos bloques IPv4 es privado según la tabla visual del curso?',options:['172.16.0.0/12','172.0.0.0/8','176.16.0.0/12'],answer:0,explain:'La lámina enumera el rango 172.16.0.0 a 172.31.255.255 como bloque privado /12.',wrong:['','Incluye muchas direcciones que no están en el bloque privado de la tabla.','176 no es el primer octeto del bloque privado indicado.'],source:ref('ip','p. 5')}
];
const FLASHCARDS=[
 ['fundamentos','¿Cuáles son los cuatro elementos de una red?','Dispositivos, medios, mensajes y reglas o protocolos.'],
 ['fundamentos','¿Qué es convergencia?','Voz, video y datos usan una infraestructura común.'],
 ['dispositivos','Switch vs router','El switch conecta equipos de una LAN; el router interconecta redes.'],
 ['medios','¿Cuándo elegir fibra monomodo?','Para enlaces de larga distancia según el ejercicio del curso.'],
 ['medios','Tres tipos de antena','Direccional, omnidireccional y sectorial.'],
 ['arquitectura','Cuatro cualidades de arquitectura','Tolerancia a fallos, escalabilidad, QoS y seguridad.'],
 ['arquitectura','¿Qué significa QoS?','Mecanismos que priorizan tráfico cuando hay congestión.'],
 ['modelos','Capas OSI de abajo arriba','Física, enlace, red, transporte, sesión, presentación, aplicación.'],
 ['modelos','Capas TCP/IP de abajo arriba','Acceso a red, Internet, transporte, aplicación.'],
 ['modelos','PDU: transporte → red → enlace','Segmento → paquete → trama.'],
 ['transporte','Apertura TCP','SYN → SYN‑ACK → ACK.'],
 ['transporte','¿Para qué sirven los puertos?','Distinguen servicios o conversaciones en un host.'],
 ['ip','¿Qué significa /24?','24 bits de red; máscara 255.255.255.0.'],
 ['ip','IPv4: longitud y escritura','32 bits expresados como cuatro octetos de 0 a 255.'],
 ['ip','¿Cuáles son los bloques IPv4 privados?','10.0.0.0/8, 172.16.0.0/12 y 192.168.0.0/16.'],
 ['ip','Máscaras históricas A, B y C','A: /8; B: /16; C: /24. En ejercicios modernos usa el prefijo CIDR explícito.'],
 ['subnetting','Subredes modernas con n bits prestados','2ⁿ subredes.'],
 ['subnetting','Hosts usuales con h bits de host','2ʰ−2 direcciones asignables; excepción para casos especiales.'],
 ['subnetting','Salto para /26 en el último octeto','256−192=64.'],
 ['ruteo','¿Qué falta para usar una ruta alternativa?','Interfaces operativas y rutas configuradas de ida y vuelta.']
].map((x,i)=>({id:'f'+i,topic:x[0],front:x[1],back:x[2]}));
const ROUTE=[['fundamentos','Comprende comunicación y protocolos'],['dispositivos','Reconoce equipos y topologías'],['medios','Elige medios según el escenario'],['arquitectura','Diseña para fallas, crecimiento, QoS y seguridad'],['modelos','Ubica capas, funciones y encapsulación'],['transporte','Distingue TCP, UDP y puertos'],['ip','Domina IPv4, máscara y CIDR'],['subnetting','Resuelve rangos y subredes'],['ruteo','Integra todo en la topología']];
